version: '2'
services:
  mysql:
    image: mysql:5.7.14
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "kplcloud"
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
    ]
    expose:
      - "3306"
    ports:
      - "3306:3306"
  redis:
      image: redis
      expose:
        - "6379"
      ports:
        - "6379:6379"
      volumes:
        - ./redis-data:/data
  rabbitmq:
    environment:
      RABBITMQ_NODENAME: "rabbitmq"
      RABBITMQ_DEFAULT_USER: "kplcloud"
      RABBITMQ_DEFAULT_PASS: "kplcloud"
    image: rabbitmq:3.6.14-management-alpine
    expose:
      - "5672"
      - "15672"
    ports:
      - "5672:5672"
      - "15672:15672"
  kplcloud:
    image: kplcloud/kplcloud
    command: /go/bin/kplcloud start -p :8080 -c /etc/kplcloud/app.cfg -k /etc/kplcloud/config.yaml
    environment:
      GOPATH: "/go"
      ADMIN_PASSWORD: "admin" # 如果是login_type: email 那这是初始化管理员的登陆密码
    volumes:
      - ../../sample-config/app.cfg-sample:/etc/kplcloud/app.cfg
      - ../../sample-config/config.yaml-sample:/etc/kplcloud/config.yaml
    depends_on:
      - mysql
      - rabbitmq
      - redis
    restart: always
    ports:
      - "8080:8080"
